version: '3.1'
services:
  db:
    image: postgres:9.5
    container_name: db
    env_file: ./docker/.env

  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: backend
    container_name: backend
    command: bash -c "sleep 5 && sh ./docker/entrypoint-prod.sh"
    env_file: 
      - ./docker/.env
    volumes:
      - .:/code
    expose:
      - "8000"
    links:
      - db
  
  nginx:
    image: nginx:latest
    container_name: nginx
    #    env_file: .env
    env_file:
      - ./docker/.env
    ports:
      - "80:80"
    links:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: unless-stopped
    command: /bin/bash -c "sleep 5 && nginx -g 'daemon off;'"
    volumes:
      - ./logs/nginx:/tmp/logs
      - ./nginx:/etc/nginx/conf.d/default.conf
      - ./web/django-static:/opt/app/django-static
      - ./media:/opt/app/media
      - ./frontend/build:/var/www/frontend # maps frontend build inside nginx
    depends_on:
      - backend

volumes:
  web-db:
