version: '3.1'
services:
  db:
    image: postgres:9.5
    container_name: db
    env_file: 
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
      
  backend:
    build: .
    image: backend
    command: bash -c "sleep 5 && sh ./entrypoint.sh"
    env_file: 
      - .env
    volumes:
      - .:/app
    ports:
      - 8000:80
    links:
      - db
  
  frontend:
    build: ./frontend
    container_name: frontend
    command: bash -c "npm run --prefix ./frontend start"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
  nginx:
    image: nginx:latest
    env_file: .env
    ports:
      - "80:80"
    links:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: unless-stopped
    command: /bin/bash -c "sleep 5 && nginx -g 'daemon off;'"
    volumes:
      - ./logs/nginx:/tmp/logs
      - ./nginx:/etc/nginx/conf.d/default.conf
      - ./static:/opt/app/static
      - ./media:/opt/app/media
    depends_on:
      - backend

volumes:
  web-db:
