version: '3.1'
services:
  db:
    image: postgres:9.5
    container_name: db
    env_file: 
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
      
  mine_backend:
    build: .
    image: mine_backend
    container_name: mine_backend
    command: bash -c "sleep 5 && sh ./entrypoint-prod.sh"
    env_file: 
      - .env
    volumes:
      - .:/app
    expose:
      - "8000"
    links:
      - db
  
  frontend:
    build: ./frontend
    container_name: frontend
    command: bash -c "npm run --prefix ./frontend start"
    volumes:
      - .:/app
  nginx:
    image: nginx:latest
    env_file: .env
    ports:
      - "80:80"
    links:
      - mine_backend
    deploy:
      replicas: 1
      restart_policy:
        condition: unless-stopped
    command: /bin/bash -c "sleep 5 && nginx -g 'daemon off;'"
    volumes:
      - ./logs/nginx:/tmp/logs
      - ./nginx:/etc/nginx/conf.d/default.conf
      - ./django-static:/opt/app/django-static
      - ./media:/opt/app/media
      - ./frontend/build:/var/www/frontend # maps frontend build inside nginx
    depends_on:
      - mine_backend

volumes:
  web-db:
