version: '3.1'
services:
  db:
    image: postgres:9.5
    container_name: db
    env_file: ./docker/.env
#    ports:
#      - 5432:5432
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: backend
    container_name: backend
    command: bash -c "sleep 4 && sh ./docker/entrypoint.sh"
    env_file: ./docker/.env
    volumes:
      - .:/code
    ports:
      - 8000:80
    ######### stdin_open and tty to debug
    stdin_open: true
    tty: true
    links:
      - db
  
  frontend:
   build: ./frontend
   container_name: frontend
   env_file: ./docker/.env
   command: bash -c "cd ./frontend && npm run start"
   volumes:
     - .:/app
   ports:
     - "3000:3000"
   stdin_open: true
   tty: true
